version: '3.2'
services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
    - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "XDG_CONFIG_HOME=/app"
    ports:
    - "80:80"
    links:
      - php-fpm
      - node
    networks:
      - my-net

  php-fpm:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "REDIS_PORT=6379"
      - "REDIS_HOST=redis"
      - "PHP_IDE_CONFIG=serverName=Docker"
    links:
      - mysql
      - node
    extra_hosts:
        - "host.docker.internal:host-gateway"
    networks:
      - my-net

  php-cli:
    build:
      context: ./
      dockerfile: docker/php-cli.docker
    volumes:
    - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "COMPOSER_MEMORY_LIMIT=-1"
    links:
      - mysql
    tty: true
    networks:
      - my-net

  mysql:
    image: mysql:8.0
    volumes:
    - ./DBDocker:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_USER=test"
      - "MYSQL_PASSWORD=12345678"
      - "MYSQL_DATABASE=laravel"
    ports:
      - "8101:3306"
    network:
      - my-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=secret
      - UPLOAD_LIMIT=64M
    restart: always
    ports:
      - 8081:80
    networks:
      - my-net

  node:
    image: node:18-alpine
    ports:
        - "3000:3000"
    volumes:
    - ./:/var/www
    working_dir: /var/www
    tty: true
    networks:
      - my-net

volumes:
  database:

networks:
  my-net:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400
